#!/bin/bash
systemctl enable bluetooth
pacman -Sy xorg --noconfirm
de=$(dialog --menu "Choose desktop environment" 10 30 30 "1" "KDE Plasma 5" "2" "Gnome" "3" "Xfce" "4" "Cinnamon" "5" "MATE" --stdout)
browser=$(dialog --menu "Choose web browser" 10 30 30 "1" "Firefox" "2" "Chromium" "3" "Waterfox G4" "4" "Vivaldi" "5" "LibreWolf" "6" "Brave" --stdout)
editor=$(dialog --menu "Choose editor" 10 30 30 "1" "nano" "2" "vim" "3" "vi" "4" "neovim" "5" "emacs" --stdout)
office=$(dialog --menu "Choose office suite" 10 30 30 "1" "LibreOffice" "2" "None" --stdout)
media=$(dialog --menu "Choose media player" 10 30 30 "1" "VLC" "2" "mpv" --stdout)
nvidia=$(dialog --yesno "Do you want to install proprietary NVIDIA drivers?" 10 30 --stdout)

if [ "$?" == "0" ]; then
    pacman -S nvidia nvidia-utils lib32-nvidia-utils
fi

useradd -m aurtemp
usermod -G sudonopasswd aurtemp

pacman -S lutris qbittorrent wine element-desktop thunderbird obs-studio gparted unzip gzip tar zstd wget curl rtkit lm_sensors --noconfirm

if [ "$de" == "1" ]; then
    pacman -S sddm plasma discover packagekit-qt5 dolphin kate konsole gwenview --noconfirm
    systemctl enable sddm
elif [ "$de" == "2" ]; then
    pacman -S gdm gnome gnome-extra --noconfirm
    systemctl enable gdm
elif [ "$de" == "3" ]; then
    pacman -S xfce4 lightdm xfce4-goodies --noconfirm
    systemctl enable lightdm
elif [ "$de" == "4" ]; then
    pacman -S cinnamon xed xreader gdm gnome-terminal nemo --noconfirm
    systemctl enable gdm
elif [ "$de" == "5" ]; then
    pacman -S mate mate-extra gdm gnome-terminal thunar --noconfirm
    systemctl enable gdm
fi

if [ "$browser" == "1" ]; then
    pacman -S firefox --noconfirm
elif [ "$browser" == "2" ]; then
    pacman -S chromium --noconfirm
elif [ "$browser" == "3" ]; then
    cd /home/aurtemp
    git clone https://aur.archlinux.org/waterfox-g4-bin.git
    chown -R aurtemp waterfox-g4-bin
    cd waterfox-g4-bin
    sudo -u aurtemp makepkg -si --noconfirm
    cd /
elif [ "$browser" == "4" ]; then
    pacman -S vivaldi --noconfirm
elif [ "$browser" == "5" ]; then
    pacman -S librewolf --noconfirm
elif [ "$browser" == "6" ]; then
    cd /home/aurtemp
    git clone https://aur.archlinux.org/brave-bin.git
    chown -R aurtemp brave-bin
    cd brave-bin
    sudo -u aurtemp makepkg -si --noconfirm
    cd /
fi

if [ "$editor" == "1" ]; then
    pacman -S nano --noconfirm
elif [ "$editor" == "2" ]; then
    pacman -S vim --noconfirm
elif [ "$editor" == "3" ]; then
    pacman -S vi --noconfirm
elif [ "$editor" == "4" ]; then
    pacman -S neovim --noconfirm
elif [ "$editor" == "5" ]; then
    pacman -S emacs --noconfirm
fi

if [ "$office" == "1" ]; then
    pacman -S libreoffice --noconfirm
fi

if [ "$media" == "1" ]; then
    pacman -S vlc --noconfirm
elif [ "$media" == "2" ]; then
    pacman -S mpv --noconfirm
fi

cd /home/aurtemp
git clone https://aur.archlinux.org/ttf-twemoji.git
chown -R aurtemp ttf-twemoji
cd ttf-twemoji
sudo -u aurtemp makepkg -si --noconfirm
cd ..
git clone https://aur.archlinux.org/ttf-ms-win11.git
chown -R aurtemp ttf-ms-win11
cd ttf-ms-win11
sudo -u aurtemp makepkg -si --noconfirm
cd /

userdel -fr aurtemp
