#!/bin/bash
useradd -m aurtemp
usermod -G sudonopasswd aurtemp
editor=$(dialog --menu "Choose editor" 10 30 30 "1" "nano" "2" "vim" "3" "vi" "4" "neovim" "5" "emacs" --stdout)
pkgs=$(dialog --checklist "Choose server packages" 20 60 40 "openssh" "SSH client and server" "on" "tmux" "Terminal multiplexer" "on" "qemu" "Virtualization software" "off" "vsftpd" "FTP server" "off" "samba" "SMB server" "off" "jre-openjdk" "OpenJDK" "off" "apache" "Apache HTTP Server" "off" "nginx" "Nginx HTTP Server" "off" "dnsmasq" "DNS, DHCP, PXE and TFTP server" "off" "nodejs" "Node.js" "off" "docker" "Docker" "off" "openvpn" "VPN client and server" "off" --stdout)
pacman -Sy $pkgs --noconfirm

if [ "$pkgs" == *"openssh"* ]; then
    systemctl enable sshd
elif [ "$pkgs" == *"vsftpd"* ]; then
    systemctl enable vsftpd
elif [ "$pkgs" == *"samba"* ]; then
    wget "https://git.samba.org/samba.git/?p=samba.git;a=blob_plain;f=examples/smb.conf.default;hb=HEAD" -O /tmp/smb.conf
    cp /tmp/smb.conf /etc/samba/smb.conf
    systemctl enable smb
elif [ "$pkgs" == *"apache"* ]; then
    systemctl enable httpd
elif [ "$pkgs" == *"nginx"* ]; then
    systemctl enable nginx
elif [ "$pkgs" == *"dnsmasq"* ]; then
    systemctl enable dnsmasq
elif [ "$pkgs" == *"docker"* ]; then
    systemctl enable docker
fi

if [ "$editor" == "1" ]; then
    pacman -S nano --noconfirm
elif [ "$editor" == "2" ]; then
    pacman -S vim --noconfirm
elif [ "$editor" == "3" ]; then
    pacman -S vi --noconfirm
elif [ "$editor" == "4" ]; then
    pacman -S neovim --noconfirm
elif [ "$editor" == "5" ]; then
    pacman -S emacs --noconfirm
fi


userdel -fr aurtemp
