#!/bin/bash
systemctl enable bluetooth
pacman -Sy xorg --noconfirm
de=$(dialog --menu "Choose edition" 10 30 30 "1" "Full" "2" "Performance" --stdout)
browser=$(dialog --menu "Choose web browser" 10 30 30 "1" "Firefox" "2" "Chromium" "3" "Brave" --stdout)
media=$(dialog --menu "Choose media player" 10 30 30 "1" "VLC" "2" "mpv" --stdout)
lspci | grep "GeForce" >/dev/null
if [ $? == 0 ]; then
    nvidia=$(dialog --yesno "Do you want to install proprietary NVIDIA drivers?" 10 30 --stdout)
fi
if [ "$?" == "0" ]; then
    pacman -S nvidia nvidia-utils lib32-nvidia-utils --noconfirm
fi

useradd -m aurtemp
usermod -G sudonopasswd aurtemp

pacman -S lutris piper qbittorrent wine wine-gecko wine-mono element-desktop gparted unzip gzip tar zstd wget curl rtkit lm_sensors nano vim steam jre-openjdk gamemode lib32-gamemode --noconfirm

wget "https://raw.githubusercontent.com/FeralInteractive/gamemode/master/example/gamemode.ini" -O gamemode.ini
mv gamemode.ini /etc/gamemode.ini

cd /home/aurtemp
git clone https://aur.archlinux.org/openrgb.git
chown -R aurtemp openrgb
cd openrgb
sudo -u aurtemp makepkg -si --noconfirm
cd /

if [ "$de" == "1" ]; then
    pacman -S sddm plasma discover packagekit-qt5 dolphin kate konsole gwenview obs-studio kdenlive ffmpeg ppsspp --noconfirm
    systemctl enable sddm
    cd /home/aurtemp
    git clone https://aur.archlinux.org/heroic-games-launcher-bin.git
    chown -R aurtemp heroic-games-launcher-bin
    cd heroic-games-launcher-bin
    sudo -u aurtemp makepkg -si --noconfirm
    cd /
elif [ "$de" == "2" ]; then
    pacman -S xfce4 lightdm xfce4-goodies --noconfirm
    systemctl enable lightdm
fi

if [ "$browser" == "1" ]; then
    pacman -S firefox --noconfirm
    elif [ "$browser" == "2" ]; then
    pacman -S chromium --noconfirm
    elif [ "$browser" == "3" ]; then
    cd /home/aurtemp
    git clone https://aur.archlinux.org/brave-bin.git
    chown -R aurtemp brave-bin
    cd brave-bin
    sudo -u aurtemp makepkg -si --noconfirm
    cd /
fi

if [ "$media" == "1" ]; then
    pacman -S vlc --noconfirm
    elif [ "$media" == "2" ]; then
    pacman -S mpv --noconfirm
fi

cd /home/aurtemp
git clone https://aur.archlinux.org/ttf-twemoji.git
chown -R aurtemp ttf-twemoji
cd ttf-twemoji
sudo -u aurtemp makepkg -si --noconfirm
cd ..
git clone https://aur.archlinux.org/ttf-ms-win11.git
chown -R aurtemp ttf-ms-win11
cd ttf-ms-win11
sudo -u aurtemp makepkg -si --noconfirm
cd /

userdel -fr aurtemp
